[workspace]

members = [
    "bin/node",
    "bin/runtime",
    "finality-aleph",
    "pallets/aleph",
    "pallets/elections",
    "pallets/support",
    "pallets/snarcos",
    "primitives",
]

exclude = [
  "flooder",
  "e2e-tests",
  "aleph-client",
  "fork-off",
  "benches/payout-stakers",
  "bin/cliain",
]
