[package]
name = "cliain"
version = "0.12.2"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
codec = { package = 'parity-scale-codec', version = "3.0.0", features = ['derive'] }
contract-metadata = "3.2.0"
contract-transcode = "3.2.0"
dialoguer = "0.10.0"
env_logger = "0.8"
hex = "0.4.3"
ink_metadata = { version = "4.3.0", features = ["derive"] }
liminal-ark-relations = { version = "0.4.0", optional = true }
log = "0.4"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

tokio = { version = "1.21.2", features = ["full"] }

pallet-staking = { git = "https://github.com/Cardinal-Cryptography/polkadot-sdk.git", branch = "aleph-v1.2.0" }
sp-core = { git = "https://github.com/Cardinal-Cryptography/polkadot-sdk.git", branch = "aleph-v1.2.0", features = ["full_crypto"] }

aleph_client = { path = "../../aleph-client" }
primitives = { path = "../../primitives" }

[features]
default = ["std"]
std = []
liminal = [
    "aleph_client/liminal",
    "liminal-ark-relations",
]
