services:
  Node0:
    extends:
      file: docker-compose.base.yml
      service: Node0
    image: aleph-node:syntheticnet
    networks:
      - synthetic-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node0:30343
    ports:
      - 3000:80

  Node1:
    extends:
      file: docker-compose.base.yml
      service: Node1
    image: aleph-node:syntheticnet
    networks:
      - synthetic-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node1:30344
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID
    ports:
      - 3001:80

  Node2:
    extends:
      file: docker-compose.base.yml
      service: Node2
    image: aleph-node:syntheticnet
    networks:
      - synthetic-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node2:30345
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID
    ports:
      - 3002:80

  Node3:
    extends:
      file: docker-compose.base.yml
      service: Node3
    image: aleph-node:syntheticnet
    networks:
      - synthetic-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node3:30346
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID
    ports:
      - 3003:80

  Node4:
    extends:
      file: docker-compose.base.yml
      service: Node4
    image: aleph-node:syntheticnet
    networks:
      - synthetic-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node4:30347
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID
    ports:
      - 3004:80

networks:
  synthetic-network:
    name: synthetic-network
    driver: bridge

