services:
  Node0:
    extends:
      file: docker-compose.base.yml
      service: Node0
    networks:
      - main
      - Node0
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node0:30343

  Node1:
    extends:
      file: docker-compose.base.yml
      service: Node1
    networks:
      - main
      - Node1
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node1:30344
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID

  Node2:
    extends:
      file: docker-compose.base.yml
      service: Node2
    networks:
      - main
      - Node2
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node2:30345
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID

  Node3:
    extends:
      file: docker-compose.base.yml
      service: Node3
    networks:
      - main
      - Node3
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node3:30346
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID

  Node4:
    extends:
      file: docker-compose.base.yml
      service: Node4
    networks:
      - main
      - Node4
    environment:
      - PUBLIC_VALIDATOR_ADDRESS=Node4:30347
      - BOOT_NODES=/dns4/Node0/tcp/30333/p2p/$BOOTNODE_PEER_ID

networks:
  main:
    name: main-network
  Node0:
    name: Node0-network
  Node1:
    name: Node1-network
  Node2:
    name: Node2-network
  Node3:
    name: Node3-network
  Node4:
    name: Node4-network
