[package]
name = "pallet-baby-liminal"
version = "0.1.0"
authors = ["Cardinal Cryptography"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
blake2 = { version = "0.9", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0", default-features = false, features = ["derive"] }
digest = "0.10"
scale-info = { version = "2.0", default-features = false, features = ["derive"] }

ark-crypto-primitives = { version = "^0.3.0", default-features = false }
ark-ec = { version = "^0.3.0", default-features = false }
ark-ff = { version = "^0.3.0", default-features = false }
ark-poly = { version = "^0.3.0", default-features = false }
ark-poly-commit = { version = "^0.3.0", default-features = false }
ark-relations = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-r1cs-std = { version = "^0.3.0", default-features = false }
ark-snark = { version = "^0.3.0", default-features = false }

ark-bls12-381 = { version = "^0.3.0" }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-gm17 = { version = "^0.3.0", default-features = false }
ark-marlin = { version = "^0.3.0", default-features = false }

frame-benchmarking = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38", optional = true }
frame-support = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }
frame-system = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }
sp-core = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }
sp-io = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }
sp-std = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }

liminal-ark-poseidon = { path = "../../poseidon", default-features = false, optional = true }
primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
sp-runtime = { default-features = false, git = "https://github.com/Cardinal-Cryptography/substrate.git", branch = "aleph-v0.9.38" }

[features]
default = ["std"]
std = [
    "ark-crypto-primitives/std",
    "ark-bls12-381/std",
    "ark-ec/std",
    "ark-ff/std",
    "ark-gm17/std",
    "ark-groth16/std",
    "ark-poly/std",
    "ark-poly-commit/std",
    "ark-relations/std",
    "ark-r1cs-std/std",
    "ark-serialize/std",
    "ark-std/std",

    "blake2/std",
    "codec/std",
    "digest/std",

    "frame-benchmarking/std",
    "frame-system/std",
    "frame-support/std",
    "sp-core/std",
    "sp-io/std",
    "sp-std/std",
    "sp-runtime/std",

    "primitives/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "liminal-ark-poseidon",
]
try-runtime = [
    "frame-support/try-runtime",
]
