[package]
name = "aleph-runtime"
version = "0.3.0"
authors = ["Cardinal Cryptography"]
edition = "2018"
license = "Apache 2.0"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

primitives = { path = "../../primitives", default-features = false }
pallet-aleph = { path = "../../pallet", default-features = false}

frame-election-provider-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
frame-executive = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}

pallet-aura = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-session = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}

sp-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-block-builder = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-consensus-aura = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-inherents = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-offchain = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-session = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-transaction-pool = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}

pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "8bbad73f5"}


[build-dependencies]
substrate-wasm-builder = { version = "4.0.0"}

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-aleph/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-session/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
    "sp-offchain/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "frame-system-rpc-runtime-api/std",
	"primitives/std",
]
