---
name: Check excluded packages

on:
  workflow_call:

jobs:
  main:
    name: Check excluded packages
    runs-on: [self-hosted, Linux, X64, large]
    env:
      CARGO_INCREMENTAL: 0
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # TODO this is not ideal, as we need this step only to have rustup in the path
      # This step install Rust wfrom root rust-toolchain.toml, which is not used later
      # by this worfklow. Action install-rust-toolchain should have optional parameter path
      # in which we pass relative path to aleph-client to read its rust-toolchain.toml file
      - name: Install Rust Toolchain
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v7

      # aleph-client and all its dependees still require nightly Rust version
      - name: Read aleph-client toolchain
        id: aleph-client-toolchain-channel
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'aleph-client/rust-toolchain.toml'
          field: 'toolchain.channel'

      - name: Read workspace excluded packages list
        id: workspace-excluded-packages
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: 'Cargo.toml'
          field: 'workspace.exclude'

      - name: Install prerequisites
        env:
          RUST_TOOLCHAIN: ${{ steps.aleph-client-toolchain-channel.outputs.value }}
        run: |
          rustup toolchain install '${{ env.RUST_TOOLCHAIN }}'
          cargo '+${{ env.RUST_TOOLCHAIN }}' \
            install aleph-zero-cargo-nono --locked

      - name: Check excluded packages
        env:
          RUSTC_WRAPPER: ""
          RUSTC_WORKSPACE_WRAPPER: sccache
        run: |
          ./.github/scripts/run_checks_on_excluded_packages.sh \
            --packages "${{ steps.workspace-excluded-packages.outputs.value }}"
