---
#  This workflow checks if vars and secrets are present and fails if one is empty.
#  It should be included as a first step in all the workflows.
name: Check vars and secrets
on:
  workflow_call:

jobs:
  main:
    name: Check available vars and secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Check vars
        run: |
          if [[ \
            -z "${{ vars.ECR_PUBLIC_HOST }}" || \
            -z "${{ vars.ECR_PUBLIC_REGISTRY }}" || \
            -z "${{ vars.DOCKERHUB_ALEPH_NODE_REPO }}" || \
            -z "${{ vars.ECR_ALEPH_NODE_REPO }}" \
          ]]; then
            echo "!!! Some repository variables are either missing or empty."
            echo "!!! Please check either repository or organization settings."
            exit 1
          fi

      - name: Check secrets
        run: |
          if [[ \
            -z "${{ secrets.ARGOCD_DEVNET_HOST }}" || \
            -z "${{ secrets.ARGO_SYNC_USER_TOKEN }}" || \
            -z "${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}" || \
            -z "${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}" || \
            -z "${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}" || \
            -z "${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}" || \
            -z "${{ secrets.AUTOCOMMIT_AUTHOR }}" || \
            -z "${{ secrets.AUTOCOMMIT_EMAIL }}" || \
            -z "${{ secrets.CI_DEVNET_S3BUCKET_NAME }}" || \
            -z "${{ secrets.CI_MAINNET_S3BUCKET_NAME }}" || \
            -z "${{ secrets.CI_GH_TOKEN }}" || \
            -z "${{ secrets.CI_S3BUCKET_NAME }}" || \
            -z "${{ secrets.DEVNET_KEYS_S3BUCKET_NAME }}" || \
            -z "${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}" || \
            -z "${{ secrets.REPO_ARGOCD_APPS_NAME }}" || \
            -z "${{ secrets.SYNCAZF }}" || \
            -z "${{ secrets.DOCKERHUB_PASSWORD }}" || \
            -z "${{ secrets.DOCKERHUB_USERNAME }}" || \
            -z "${{ secrets.SLACK_WEBHOOK_NIGHTLY_PIPELINE }}" || \
            -z "${{ secrets.SLACK_WEBHOOK_TRACK_APPLICATIONS }}" || \
            -z "${{ secrets.SLACK_WEBHOOK_DEV_ONDUTY }}"
          ]]; then
            echo "!!! Some repository secrets are either missing or empty."
            echo "!!! Please check either repository or organization settings."
            exit 1
          fi
