---
name: Build and push cliain docker image

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build-image:
    name: Build binary
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        runtime: [standard, liminal]
      fail-fast: false
    env:
      ECR_PUBLIC_HOST: ${{ vars.ECR_PUBLIC_HOST }}
      ECR_PUBLIC_REGISTRY: ${{ vars.ECR_PUBLIC_REGISTRY }}
      AWS_MAINNET_ACCESS_KEY_ID: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
      AWS_MAINNET_SECRET_ACCESS_KEY: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
    steps:
      - name: GIT | Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain

      - name: Cargo | Build release binary
        run: |
          if [[ ${{ matrix.runtime }} = 'liminal' ]]; then
            FEATURES="--features liminal"
          fi
          cd ./bin/cliain && cargo build --release ${FEATURES}

      - name: Test SNARK relations
        if: ${{ matrix.runtime == 'liminal' }}
        run: ./.github/scripts/test_cliain_snark_relations.sh

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: Login to ECR
        if: >
          env.ECR_PUBLIC_HOST != '' &&
          env.ECR_PUBLIC_REGISTRY != '' &&
          env.AWS_MAINNET_ACCESS_KEY_ID != '' &&
          env.AWS_MAINNET_SECRET_ACCESS_KEY != ''
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_PUBLIC_HOST }}
          username: ${{ env.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ env.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: Build and push latest docker image
        if: >
          env.ECR_PUBLIC_HOST != '' &&
          env.ECR_PUBLIC_REGISTRY != '' &&
          env.AWS_MAINNET_ACCESS_KEY_ID != '' &&
          env.AWS_MAINNET_SECRET_ACCESS_KEY != ''
        id: build-image
        env:
          REGISTRY: ${{ env.ECR_PUBLIC_REGISTRY }}
          IMAGE_NAME: ${{ matrix.runtime == 'standard' && 'cliain' || 'cliain-liminal' }}
          TAG: ${{ matrix.runtime == 'standard' &&
               (steps.get-ref-properties.outputs.branch-name-flattened == 'main' && 'latest' ||
               steps.get-ref-properties.outputs.branch-name-flattened) ||
               matrix.runtime == 'liminal' && steps.get-ref-properties.outputs.sha }}
        run: |
          docker build -t "${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ env.TAG }}" \
            -f ./bin/cliain/Dockerfile ./bin/cliain
          if [[ \
            "${{ github.event_name }}" == "workflow_dispatch" || \
            "${{ github.event_name }}" == "push" \
          ]]; then
             docker push "${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          fi
