name: Nightly pipeline

on:
  schedule:
    - cron:  '00 23 * * *'

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}-nightly"
  cancel-in-progress: true

jobs:
  build-new-node:
    name: Build node and runtime artifacts (PR version)
    uses: ./.github/workflows/build-node-and-runtime.yml
    secrets: inherit

  build-test-docker:
    needs: [build-new-node]
    name: Build docker image with the test node artifact
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Download test artifact
        uses: actions/download-artifact@v2
        with:
          name: aleph-test-node
          path: target/release

      - name: Build test docker image
        id: build-image
        run: |
          chmod +x target/release/aleph-node
          docker build --tag aleph-node:latest -f ./docker/Dockerfile .
          docker save -o aleph-node.tar aleph-node:latest

      - name: Upload test docker image
        uses: actions/upload-artifact@v2
        with:
          name: aleph-test-docker
          path: aleph-node.tar
          if-no-files-found: error
          retention-days: 7

  build-synthetic-network-docker:
    needs: [build-test-docker]
    name: Build docker image with the test node artifact and support for synthetic-network
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Download artifact with docker image for aleph-node
        uses: actions/download-artifact@v2
        with:
          name: aleph-test-docker

      - name: Load node docker image
        shell: bash
        run: docker load -i aleph-node.tar

      - name: Build test docker image
        id: build-image
        run: |
          scripts/synthetic-network/build_synthetic-network.sh
          docker save -o aleph-node.tar aleph-node:syntheticnet

      - name: Upload test docker image
        uses: actions/upload-artifact@v2
        with:
          name: aleph-test-synthetic-docker
          path: aleph-node.tar
          if-no-files-found: error
          retention-days: 7

  check-determinism:
    needs: [build-new-node]
    name: Verify runtime build determinism
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: aleph-release-runtime

      - name: Build runtime and compare checksum with artifact
        env:
          ARTIFACT: aleph_runtime.compact.wasm
          TARGET_DIR: target/production/wbuild/aleph-runtime
        run: |
          mkdir -p "$TARGET_DIR"
          mv "$ARTIFACT" "$TARGET_DIR"
          sha256sum "$TARGET_DIR/$ARTIFACT" > checksum.sha256
          cargo clean
          cargo build --profile production -p aleph-runtime
          sha256sum -c checksum.sha256

  build-test-client:
    name: Build e2e test client suite
    runs-on: ubuntu-20.04
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore cache
        uses: ./.github/actions/restore-cache
        with:
          target-key: e2e
          cargo-key: e2e
          cache-version: v2
          cargo-targets: e2e-tests/target/

      - name: Build binary and docker image
        run: |
          cd e2e-tests/
          rm -f target/release/deps/aleph_e2e_client*
          cp $(cargo test --no-run --release --message-format=json | jq -r .executable | grep aleph_e2e_client) target/release/aleph-e2e-client
          docker build --tag aleph-e2e-client:latest -f Dockerfile .
          docker save -o aleph-e2e-client.tar aleph-e2e-client:latest

      - name: Stop cache
        uses: ./.github/actions/post-cache

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aleph-e2e-client
          path: e2e-tests/aleph-e2e-client.tar
          if-no-files-found: error
          retention-days: 7

  run-e2e-high-out-latency:
    needs: [build-synthetic-network-docker, build-test-client]
    name: Run high out-latency test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run e2e test
        uses: ./.github/actions/run-e2e-test
        with:
          test-case: high_out_latency_for_all
          image-path: aleph-test-synthetic-docker
          node-image: aleph-node:syntheticnet
          compose-file: docker/docker-compose.synthetic-network.yml
        timeout-minutes: 30

  run-e2e-no-quorum-without-high-out-latency:
    needs: [build-synthetic-network-docker, build-test-client]
    name: Run high out-latency for every quorum
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run e2e test
        uses: ./.github/actions/run-e2e-test
        with:
          test-case: high_out_latency_for_each_quorum
          image-path: aleph-test-synthetic-docker
          node-image: aleph-node:syntheticnet
          compose-file: docker/docker-compose.synthetic-network.yml
        timeout-minutes: 15

  check-e2e-test-suite-completion:
    needs: [
      run-e2e-high-out-latency,
      run-e2e-no-quorum-without-high-out-latency,
    ]
    name: Check e2e test suite completion
    runs-on: ubuntu-20.04
    steps:
      - name: All e2e tests completed
        run: echo "All e2e tests completed."

  slack:
    name: Slack notification
    runs-on: ubuntu-20.04
    needs: [check-e2e-test-suite-completion, check-determinism]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Slack message
        uses: ./.github/actions/slack-notification
        with:
          notify-on: "always"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_NIGHTLY_PIPELINE }}
